spring.application.name=QuantityMeasurementApplication
server.port=8080

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/quantitymeasurementdb
spring.datasource.username=root
spring.datasource.password=your_password

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=mySecretKey123456789012345678901234567890
jwt.expiration=86400000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=866126800297-hohmm42b2m7l9k3ai4nmtpogr4hpd9pf.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=your-google-client-secret-here
spring.security.oauth2.client.registration.google.scope=email,profile